export const GET_DOGS = "GET_DOGS"

export const FILTER_BY_CREATED = "FILTER_BY_CREATED"

export const FILTER_BY_TEMPERAMENT = "FILTER_BY_TEMPERAMENT"

export const ORDER_BY_NAME = "ORDER_BY_NAME"

export const GET_NAME_DOGS = "GET_NAME_DOGS"

export const POST_DOG = "POST_DOG"

export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS"

export const FILTER_BY_WEIGHT = "SORT_BY_WEIGHT"

export const GET_DOG_DETAIL = "GET_DOG_DETAIL"